version: 0.1

environment_variables:
  plaintext:
    DJANGO_SETTINGS_MODULE: config.settings.test
    SECRET_KEY: nosecret
    DATABASE_DEFAULT_URL: sqlite:///db1.sqlite3
    DATABASE_STREAMDATA_URL: sqlite:///db2.sqlite3
    STREAM_INCOMING_PRIVATE_KEY: changeme
    STREAM_INCOMING_PUBLIC_KEY: changeme
    OPBEAT_ENABLED: False
    GOOGLE_API_KEY: YOUR API KEY
    WHEREBY_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmFwcGVhci5pbiIsImF1ZCI6Imh0dHBzOi8vYXBpLmFwcGVhci5pbi92MSIsImV4cCI6OTAwNzE5OTI1NDc0MDk5MSwiaWF0IjoxNzExMTk0MDk4LCJvcmdhbml6YXRpb25JZCI6MjIwMzQ2LCJqdGkiOiI2NjRhNTQ4YS03ZjA5LTRjMjgtODQ2Mi0yNjdlZDQyMzdmMDYifQ.-g6E1H-ynYzqDBRHzlC1dmIJdYY7sryqTtHc83xArJA

phases:
  pre_build:
    commands:
      - echo Prebuild ops
      - pip install -r requirements.txt
  build:
    commands:
      - echo Building the application 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
